### ISSUE TITLE
Remove /detail route for conversations

### ISSUE THREAD

**Issue by louije** [vivesvoies/court-message#115]
Not used.

**Comment by louije** [comment]
So: currently, when we visit `/team-name/conversations/:id`, we actually call `ConversationsController#index`. This means hitting Reload keeps the side bar.

But the other `/team-name/***/` sub-routes (that show the contacts or the team members), if you hit "Reload"... it will show you the view full screen, without the side bar.

@alallema, je propose qu'on modifie `ContactsController` et `TeamsController` de telle sorte qu'on se retrouve toujours avec la sidebar si on fait ⌘R.

**Comment by alallema** [comment]
>  if you hit "Reload"... it will show you the view full screen, without the side bar.
Oui je l'ai noté quelque part dans une PR il me semble, mais surtout pour l'instant la navigation est pas faite :/
