### ISSUE TITLE
bug: Flaky test

### ISSUE THREAD

**Issue by alallema** [vivesvoies/court-message#119]
## Description:
There's a test that randomly fails every other time:
[here](https://github.com/vivesvoies/court-message/actions/runs/7918673162/job/21617657993?pr=118#step:6:173)
[here](https://github.com/vivesvoies/court-message/actions/runs/7905457395/job/21578135151#step:6:235)
[here](https://github.com/vivesvoies/court-message/actions/runs/8080186143/job/22077374081?pr=118#step:6:367)

I haven't had time to look, but it seems to be linked to the factories and the team's unique name.

**Comment by louije** [comment]
Curious, never got this one. It's... not a very important test (it tests that the factories are working correctly), but it's still strange. Wonder if it has something to do with the random seed used by Github Actions (possible), or the db not being cleaned up between runs (highly improbable).

**Comment by louije** [comment]
Disabled test during CI.

**Comment by alallema** [comment]
> Disabled test during CI.
C'est à dire ?

**Comment by louije** [comment]
Cf. https://github.com/vivesvoies/court-message/blob/main/test/lint_factories_test.rb.
