### ISSUE TITLE
Mettre à jour les mails d'invitation

### ISSUE THREAD

**Issue by louije** [vivesvoies/court-message#148]
Supprimer l'url inutile et les balises html

**Comment by alallema** [comment]
L'url a été supprimé dans le mail. Les balises et la date sont liés à la local de `devise_invitable`. J'ai fait une [PR](https://github.com/scambra/devise_invitable/pull/905) sur le repo qui a été merge mais je ne sais pas trop quand il fait des releases.

**Comment by louije** [comment]
Il a l'air de pas faire de releases du tout, on devrait mettre la ref du dernier commit dans le Gemfile

`gem "devise_invitable", git: "https://github.com/scambra/devise_invitable.git", ref: "d2b93edb8bf6e4ac81fa15ff4b948eafe1d456fc"`

**Comment by alallema** [comment]
Bonne idée je vais le rajouter ans la PR !

**Comment by alallema** [comment]
@louije cela dit y a des tags. Je vais ouvrir une issue pour pas qu'on oublie d'enlever la ref de commit au prochain tag
