### ISSUE TITLE
Fix: message de confirmation suppression d'un modèle

### ISSUE THREAD

**Issue by FrancoisHuguet** [vivesvoies/court-message#194]
Lorsque l'on supprime un modèle, on a un message en anglais, peut-on le modifier ?
![Capture d’écran 2024-04-11 à 18 25 56](https://github.com/vivesvoies/court-message/assets/28983018/dff0107c-d2f4-49cc-a70c-aff53fbf72d6)

**Comment by FrancoisHuguet** [comment]
et dire plutôt : êtes vous sur*es ?

**Comment by louije** [comment]
@alallema c'est facile de changer le texte, mais je me demande si on peut pas aller plus loin et utiliser https://github.com/RoleModel/turbo-confirm, qui ne passe pas par un vilain dialogue du navigateur.

**Comment by alallema** [comment]
@louije, j'ai ouvert cette PR #221 qui modifie uniquement les textes en français. J'ai regarder le `@rolemodel/turbo-confirm` mais c'est un paquet `npm` je suis pas sure que ce soit ce qu'on veuille et que ça s'applique facilement à notre app.

**Comment by alallema** [comment]
Done
