### ISSUE TITLE
Echec suppression d'une fiche contact 

### ISSUE THREAD

**Issue by ZoeAegerter** [vivesvoies/court-message#238]
ça veut pas, un écran s'affiche : "We are sorry, but something was wrong"

**Comment by alallema** [comment]
@ZoeAegerter, sur court-message.fr ou alpha.court-message.fr ? On a fait pas mal de modifications je merge tout sur court-message.fr voir si ça règle le problème.

**Comment by alallema** [comment]
Effectivement cela déclenche une erreur 500. Je ferme cette issue au profit de la #252
