### ISSUE TITLE
Add crash detection and notification

### ISSUE THREAD

**Issue by alallema** [vivesvoies/court-message#241]
## Description:
We need to implement a crash detection and notification system to improve the reliability and maintainability of our application. The implementation should include the following features:

**Crash Detection and Notification:**

- [ ] Integrate the exception_notification gem into the application to handle error notifications.
- [ ] Configure the gem to send detailed error emails, including stack traces, to the development team.

**Create Shortcut for Scalingo Reboot:**

- [ ] Implement a shortcut or script to quickly reboot the application on Scalingo. This will help in promptly recovering from crashes or downtime.

**Uptime Check:**

- [ ] Set up an uptime monitoring service to regularly check the availability of the application.
- [ ] Ensure that any downtime or performance issues are promptly reported to the development team.

**Notes:**
Check this gem: [exception notification](https://github.com/smartinez87/exception_notification)

**Comment by louije** [comment]
Gonna use Sentry for most of this!

**Comment by louije** [comment]
And https://github.com/upptime/upptime too!

**Comment by louije** [comment]
So, https://github.com/vivesvoies/court-message-uptime/ and https://vivesvoies.github.io/court-message-uptime/ should do the trick. I'll try using the GitHub app on mobile to get notifications.

**Comment by louije** [comment]
Waiting for your review, @alallema, I'll let you close.

**Comment by alallema** [comment]
Perfect, it seems to be working properly and I'm already receiving notifications.
