### ISSUE TITLE
Bug : à rajouter sur la page sign in

### ISSUE THREAD

**Issue by FrancoisHuguet** [vivesvoies/court-message#63]
Sur la page Sign In (https://alpha.court-message.fr/users/sign_in) 

rajouter logo, texte explicatif sur ce qu'est court message et logos des partenaires.

**Comment by louije** [comment]
En attente du logo.

**Comment by louije** [comment]
Pour le texte :

> Court-Messages est un outil collaboratif d’envoi et de réception de sms. Il a été conçu pour faciliter le dialogue, la médiation à distance et l’auto-suivi des personnes. 

marche ?

**Comment by alallema** [comment]
@FrancoisHuguet, @louije, il manque quoi sur cette issue ?

**Comment by louije** [comment]
je la ferme
