### ISSUE TITLE
🍔   Setup CI/CD and Deployment Tooling

### ISSUE THREAD

**Issue by louije** [vivesvoies/court-message#90]
## Description:
Some tools are required to improve teamwork on this project and ensure greater development stability.

## Todo:
- [x] #102
- [x] #103
- [x] #56
- [x] #104
- [x] #105
- [ ] #114
- [x] #106
- [x] Implement mail confirmation & invitation in Avo

Notes:
 Check linter `erb` file

**Comment by alallema** [comment]
Everything is done except implementing a seed with factory bot

**Comment by louije** [comment]
yayyy
